force-app/main/default/objects/Contract/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Migrated_Contract__c.field-meta.xml
<CustomField>
    <fullName>Migrated_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migrated Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Sales_Orders_Created__c.field-meta.xml
<CustomField>
    <fullName>Sales_Orders_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Only for Migrated Contracts</inlineHelpText>
    <label>Sales Orders Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Installation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_End_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_End_date__c</fullName>
    <label>Installation End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Order_Status__c</fullName>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Implementation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Future Terminated</fullName>
            </value>
            <value>
                <fullName>Termination Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Start_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_date__c</fullName>
    <label>Installation Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 3)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria.Please select Invoice Account</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Replica Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contract_Customer__c</field>
            <operation>equals</operation>
            <valueField>Account.B2B_Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Invoice account)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Package__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contract_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/Installation_Line__c.object-meta.xml
<CustomObject>
    <label>Installation Line</label>
    <nameField>
        <label>Installation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Line__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <formula>TEXT(Contract__r.Billing_Frequency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateSalesOrders.cls
public class CreateSalesOrders
{
    @AuraEnabled
    public static String createSORecords(Id conId)
    {
        try
        {
            List<Sales_Order__c> soList = [SELECT Id, Name FROM Sales_Order__c WHERE Contract__c = :conId];
            if(soList != NULL && !soList.isEmpty())
            {
                delete soList;
            }
            List<Installation_Line__c> existingInstLineList = [SELECT Id, Name FROM Installation_Line__c WHERE Installation__r.Contract__c = :conId];
            if(existingInstLineList != NULL && !existingInstLineList.isEmpty())
            {
                delete existingInstLineList;
            }
            List<SBQQ__Subscription__c> subList = [SELECT Id, Name, SBQQ__Product__c,SBQQ__Product__r.Name, SBQQ__Contract__c, SBQQ__Contract__r.CurrencyIsoCode, Package__c, SBQQ__Contract__r.Billing_Frequency__c, SBQQ__Contract__r.ContractTerm, SBQQ__Contract__r.Migrated_Contract__c, SBQQ__StartDate__c, SBQQ__EndDate__c, SBQQ__Quantity__c, SBQQ__NetPrice__c,CurrencyIsoCode FROM SBQQ__Subscription__c WHERE SBQQ__Contract__c = :conId];
            System.debug('subList --> ' + subList);
            Map<Id, List<SBQQ__Subscription__c>> packIdSubsListMap = new Map<Id, List<SBQQ__Subscription__c>>();
            for(SBQQ__Subscription__c sub : subList)
            {
                if(packIdSubsListMap.get(sub.Package__c) == NULL)
                {
                    packIdSubsListMap.put(sub.Package__c, new List<SBQQ__Subscription__c>());
                }
                packIdSubsListMap.get(sub.Package__c).add(sub);
            }
            List<Package__c> packList = [SELECT Id, Name FROM Package__c WHERE Id IN :packIdSubsListMap.keySet()];
            List<Installation__c> instList = [SELECT Id, Name, Package__c FROM Installation__c WHERE Package__c IN :packIdSubsListMap.keySet() AND Contract__c = :conId AND Installation_Order_Status__c = 'Active' AND Package__c != NULL];
            Map<Id, List<Installation__c>> packIdInstListMap = new Map<Id, List<Installation__c>>();
            for(Installation__c inst : instList)
            {
                if(packIdInstListMap.get(inst.Package__c) == NULL)
                {
                    packIdInstListMap.put(inst.Package__c, new List<Installation__c>());
                }
                packIdInstListMap.get(inst.Package__c).add(inst);
            }
            List<Installation_Line__c> instLineList = new List<Installation_Line__c>();
            for(SBQQ__Subscription__c sub : subList)
            {
                if(packIdInstListMap.get(sub.Package__c) != NULL)
                {
                    for(Installation__c inst : packIdInstListMap.get(sub.Package__c))
                    {
                    
                        Installation_Line__c instLine = new Installation_Line__c();
                        instLine.Installation__c = inst.Id;
                        instLine.Name = sub.SBQQ__Product__r.Name;
                        instLine.Product__c = sub.SBQQ__Product__c;
                        instLine.Net_Total__c = sub.SBQQ__NetPrice__c;
                        instLine.CurrencyIsoCode = sub.SBQQ__Contract__r.CurrencyIsoCode;
                        instLine.Subscription__c = sub.Id;
                        instLine.Start_Date__c = sub.SBQQ__StartDate__c;
                        instLine.End_Date__c = sub.SBQQ__EndDate__c;
                        instLineList.add(instLine);
                        
                    }
                }
            }
            if(!instLineList.isEmpty())
            {
                System.debug('instLineList --> ' + instLineList);
                insert instLineList;
            }
            List<Installation__c> installations = [
                SELECT Id, Name, Quote__c, Contract__c, Contract__r.Billing_Frequency__c, 
                Contract__r.ContractTerm, Contract__r.StartDate, Contract__r.EndDate, 
                Installation_Start_date__c, Installation_End_date__c, 
                Invoice_Account__c, CurrencyIsoCode 
                FROM Installation__c 
                WHERE Contract__c = :conId AND Installation_Order_Status__c = 'Active'
            ];
            CreateSalesOrderService.createSORecords(installations);
            //CreateSalesOrderService.createSOIRecords(installations);
            Contract cont = new Contract(
                Id = conId,
                Sales_Orders_Created__c = TRUE
            );
            update cont;
            return 'SUCCESS';
        }
        catch(Exception ex)
        {
            System.debug('Exception --> ' + ex);
            System.debug('Exception Line --> ' + ex.getLineNumber());
            Logger.error(ex.getMessage() + '\n\n' + ex.getLineNumber() + '\n\n' + ex.getStackTraceString());
            return 'ERROR' + ex.getMessage() + ' - ' + ex.getLineNumber();
        }
    }
}