force-app/main/default/objects/Contract/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Installation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/DeleteInstallationLinesAndSOs__c.field-meta.xml
<CustomField>
    <fullName>DeleteInstallationLinesAndSOs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DeleteInstallationLinesAndSOs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_End_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_End_date__c</fullName>
    <label>Installation End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Order_Status__c</fullName>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Implementation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Future Terminated</fullName>
            </value>
            <value>
                <fullName>Termination Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Start_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_date__c</fullName>
    <label>Installation Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 3)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria.Please select Invoice Account</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Replica Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contract_Customer__c</field>
            <operation>equals</operation>
            <valueField>Account.B2B_Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Invoice account)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Package__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contract_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Quote_Line_Group__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Group</label>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/Installation_Line__c.object-meta.xml
<CustomObject>
    <label>Installation Line</label>
    <nameField>
        <label>Installation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Line__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <formula>TEXT(Contract__r.Billing_Frequency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ActivateInstallationController.cls
public with sharing class ActivateInstallationController {

    @AuraEnabled
    public static String activateInstallation(String recId, Date startDate) {
    SavePoint sp = Database.setSavePoint();
    try {
        Logger.info('Starting activateInstallation. Record ID: ' + recId + ', Start Date: ' + startDate);

        Installation__c inst = [
            SELECT Id, Name, Contract__c, Quote_Line_Group__c, Package__c, Order__c,
                Contract__r.StartDate, Contract__r.EndDate, Contract__r.Billing_Frequency__c, Contract__r.ContractTerm,
                Installation_End_Date__c, Installation_Start_Date__c, Invoice_Account__c, CurrencyIsoCode
            FROM Installation__c
            WHERE Id = :recId
            LIMIT 1
        ];

        Logger.info('Fetched Installation: ' + inst.Name + ', Contract Start: ' + inst.Contract__r.StartDate + ', End: ' + inst.Contract__r.EndDate);
        Logger.saveLog();
        
        inst.Installation_Start_Date__c = startDate;
        inst.Installation_End_Date__c = inst.Contract__r.EndDate;
        update inst;

        deleteExistingInstallationLinesAndSalesOrders(inst.Id);

        List<SBQQ__Subscription__c> subscriptions = fetchSubscriptionsFromOrderItems(inst.Quote_Line_Group__c, inst.Package__c, inst.Order__c);
        Logger.info('Fetched ' + subscriptions.size() + ' subscriptions from Order Items.');
        Logger.saveLog();

        if (!subscriptions.isEmpty()) {
            createInstallationLines(inst, subscriptions, startDate);
        } else {
            Logger.warn('No subscriptions found. Skipping Installation Line creation.');
            Logger.saveLog();
        }

        inst.Installation_Order_Status__c = 'Active';
        update inst;

        SalesOrderGeneratorService.generateSalesOrders(new List<Installation__c>{inst}, false, false);
        Logger.info('Sales Orders generated for Installation: ' + inst.Id);

        Logger.saveLog();
        return 'SUCCESS';

    } catch (Exception ex) {
        Database.rollback(sp);
        Logger.error('Error in activateInstallation: ' + ex.getMessage() + '\n' + ex.getStackTraceString());
        Logger.saveLog();
        throw new AuraHandledException('Installation activation failed: ' + ex.getMessage());
    }
}

    private static void deleteExistingInstallationLinesAndSalesOrders(Id installationId) {
        List<Sales_Order__c> relatedSOs = [SELECT Id FROM Sales_Order__c WHERE Installation__c = :installationId and Installation__r.DeleteInstallationLinesAndSOs__c = true];
        if (!relatedSOs.isEmpty()) delete relatedSOs;

        List<Installation_Line__c> existingLines = [SELECT Id FROM Installation_Line__c WHERE Installation__c = :installationId AND Installation__r.DeleteInstallationLinesAndSOs__c = true];
        if (!existingLines.isEmpty()) delete existingLines;
    }

    private static List<SBQQ__Subscription__c> fetchSubscriptionsFromOrderItems(Id quoteLineGroupId, Id packageId, Id orderId) {
        List<OrderItem> orderItems = [
            SELECT Id FROM OrderItem
            WHERE Quote_Line_Group_ID__c = :quoteLineGroupId AND OrderId = :orderId
        ];

        if (orderItems.isEmpty()) return new List<SBQQ__Subscription__c>();

        Set<Id> orderItemIds = new Set<Id>();
        for (OrderItem oi : orderItems) orderItemIds.add(oi.Id);

        return [
            SELECT Id, Name, SBQQ__Product__c, SBQQ__Product__r.Name, SBQQ__NetPrice__c,
                   SBQQ__SegmentStartDate__c, SBQQ__SegmentEndDate__c, CurrencyIsoCode,
                   SBQQ__OrderProduct__c, SBQQ__QuoteLine__c,SBQQ__StartDate__c,SBQQ__EndDate__c
            FROM SBQQ__Subscription__c
            WHERE SBQQ__OrderProduct__c IN :orderItemIds
        ];
    }

    public static void createInstallationLines(Installation__c inst, List<SBQQ__Subscription__c> subscriptions, Date installationStartDate) {
        Logger.info('--- START createInstallationLines for Installation: ' + inst.Id + ' ---');
        Logger.info('Installation Start Date: ' + installationStartDate + ', End Date: ' + inst.Installation_End_Date__c);
        Logger.info('Total subscriptions received: ' + subscriptions.size());
        Logger.saveLog();
    
        List<Installation_Line__c> instLines = new List<Installation_Line__c>();
        Date installationEndDate = inst.Installation_End_Date__c;
    
        // Group subscriptions by SBQQ__Product__c
        Map<Id, List<SBQQ__Subscription__c>> subsByProduct = new Map<Id, List<SBQQ__Subscription__c>>();
        for (SBQQ__Subscription__c sub : subscriptions) {
            if (!subsByProduct.containsKey(sub.SBQQ__Product__c)) {
                subsByProduct.put(sub.SBQQ__Product__c, new List<SBQQ__Subscription__c>());
            }
            subsByProduct.get(sub.SBQQ__Product__c).add(sub);
        }
        Logger.info('Grouped subscriptions by product. Product groups: ' + subsByProduct.keySet().size());
        Logger.saveLog();
    
        for (Id productId : subsByProduct.keySet()) {
            List<SBQQ__Subscription__c> productSubs = subsByProduct.get(productId);
    
            // Sort subscriptions by SBQQ__SegmentStartDate__c
            productSubs.sort(); // Assumes subscriptions are comparable (or sort logic is defined elsewhere)
    
            Boolean isFirst = true;
    
            for (SBQQ__Subscription__c sub : productSubs) {
                //Date subStart = sub.SBQQ__SegmentStartDate__c;
                //Date subEnd = sub.SBQQ__SegmentEndDate__c;
                Date subStart = (sub.SBQQ__SegmentStartDate__c != null) ? sub.SBQQ__SegmentStartDate__c : sub.SBQQ__StartDate__c;
                Date subEnd   = (sub.SBQQ__SegmentEndDate__c != null) ? sub.SBQQ__SegmentEndDate__c : sub.SBQQ__EndDate__c;
    
                if (installationEndDate < subStart || installationStartDate > subEnd) continue;
    
                Date lineStart;
                if (isFirst && installationStartDate < subStart) {
                    lineStart = installationStartDate;
                } else {
                    lineStart = (installationStartDate > subStart) ? installationStartDate : subStart;
                }
    
                Date lineEnd = (installationEndDate < subEnd) ? installationEndDate : subEnd;
    
                Boolean needsProration = (lineStart > subStart || lineEnd < subEnd || (isFirst && installationStartDate < subStart));
    
                Decimal netTotal = needsProration
                    ? calculateProratedAmount(sub.SBQQ__NetPrice__c, subStart, subEnd, lineStart, lineEnd)
                    : sub.SBQQ__NetPrice__c;
    
                Logger.info('Creating line for Product: ' + sub.SBQQ__Product__r.Name +
                            ', Proration: ' + needsProration +
                            ', Line Start: ' + lineStart + ', Line End: ' + lineEnd +
                            ', Net Total: ' + netTotal);
    
                instLines.add(new Installation_Line__c(
                    Name = sub.SBQQ__Product__r.Name,
                    Installation__c = inst.Id,
                    Subscription__c = sub.Id,
                    Quote_Line__c = sub.SBQQ__QuoteLine__c,
                    Product__c = sub.SBQQ__Product__c,
                    Start_Date__c = lineStart,
                    End_Date__c = lineEnd,
                    CurrencyIsoCode = sub.CurrencyIsoCode,
                    Net_Total__c = netTotal
                ));
    
                isFirst = false;
            }
        }
    
        if (!instLines.isEmpty()) {
            Logger.info('Total Installation Lines to insert: ' + instLines.size());
            insert instLines;
            Logger.info('Inserted Installation Lines for Installation: ' + inst.Id);
            Logger.saveLog();
        } else {
            Logger.warn('No Installation Lines generated for Installation: ' + inst.Id);
            Logger.saveLog();
        }
    
        Logger.info('--- END createInstallationLines for Installation: ' + inst.Id + ' ---');
        Logger.saveLog();
    }
	
    @TestVisible
    private static Decimal calculateProratedAmount(Decimal netPrice, Date segStart, Date segEnd, Date lineStart, Date lineEnd) {
        try {
            Boolean isMonthlyAligned =
                segStart.day() == 1 &&
                segEnd == segStart.addMonths(segStart.monthsBetween(segEnd)).addDays(-1) &&
                lineStart.day() == 1 &&
                lineEnd == lineStart.addMonths(lineStart.monthsBetween(lineEnd)).addDays(-1);
    
            if (isMonthlyAligned) {
                Decimal totalMonths = (Decimal) segStart.monthsBetween(segEnd) + 1;
                Decimal lineMonths = (Decimal) lineStart.monthsBetween(lineEnd) + 1;
                return (lineMonths / totalMonths) * netPrice;
            } else {
                Decimal totalDays = segStart.daysBetween(segEnd) + 1;
                Decimal lineDays = lineStart.daysBetween(lineEnd) + 1;
                return (lineDays / totalDays) * netPrice;
            }
        } catch (Exception ex) {
            Logger.error('Error in calculateProratedAmount: ' + ex.getMessage() + '\n' + ex.getStackTraceString());
            Logger.saveLog();
            return 0;
        }
    }
}