force-app/main/default/objects/Contract/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Installation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Auto_Installation_Termination_Error__c.field-meta.xml
<CustomField>
    <fullName>Auto_Installation_Termination_Error__c</fullName>
    <label>Auto Installation/Termination Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_End_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_End_date__c</fullName>
    <label>Installation End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Order_Status__c</fullName>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Implementation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Future Terminated</fullName>
            </value>
            <value>
                <fullName>Termination Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Start_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_date__c</fullName>
    <label>Installation Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Type__c.field-meta.xml
<CustomField>
    <fullName>Installation_Type__c</fullName>
    <label>Installation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vessel</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Package__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contract_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Termination_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Termination_End_Date__c</fullName>
    <label>Termination End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Termination_Reason__c.field-meta.xml
<CustomField>
    <fullName>Termination_Reason__c</fullName>
    <inlineHelpText>Max 10000 characters</inlineHelpText>
    <label>Termination Reason</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Vessel_Name__c.field-meta.xml
<CustomField>
    <fullName>Vessel_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel Name</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/Installation_Line__c.object-meta.xml
<CustomObject>
    <label>Installation Line</label>
    <nameField>
        <label>Installation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Line__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <formula>TEXT(Contract__r.Billing_Frequency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Credit_Note__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credit Note</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Original_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Original_Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Original Sales Orders</relationshipLabel>
    <relationshipName>Original_Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unbilled</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fulfilment</fullName>
            </value>
            <value>
                <fullName>Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Pending Billing/Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/Sales_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Item__c/fields/Installation_Line__c.field-meta.xml
<CustomField>
    <fullName>Installation_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Line</label>
    <referenceTo>Installation_Line__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InstallationTriggerHandlerTest.cls
@IsTest
private class InstallationTriggerHandlerTest {

    @TestSetup
    static void setupOrgDefaults() {
        TestDataFactory_OTG.enableOrgVRConfig();
        TestDataFactory_OTG.primeDefaultOwnerAllRegions(UserInfo.getUserId());

        VRConfiguration__c config = VRConfiguration__c.getOrgDefaults();
        if (config == null) {
            config = new VRConfiguration__c();
        }
        //config.ByPass_Account_Triggers__c = true;
        //config.ByPass_Contract_Triggers__c = true;
       // config.ByPass_Opportunity_Triggers__c = true;
       // config.ByPass_Flow__c = true;
        upsert config;
    }

    @IsTest
    static void testBeforeInsertPreventsDuplicateVesselInstallation() {
        TestDataFactory_OTG.OrderContext ctx =
            TestDataFactory_OTG.buildOrderContext('Americas', 'Amendment', 'Draft', true, false);

        Installation__c existing = [
            SELECT Id, Package__c, Vessel_Name__c, Quote__c
            FROM Installation__c
            WHERE Id = :ctx.installation.Id
        ];

        update new Installation__c(
            Id = existing.Id,
            Installation_Order_Status__c = 'Active',
            Installation_Type__c = 'Vessel',
            Vessel_Name__c = existing.Vessel_Name__c
        );

        Installation__c duplicate = new Installation__c(
            Package__c = existing.Package__c,
            Installation_Type__c = 'Vessel',
            Vessel_Name__c = existing.Vessel_Name__c,
            Installation_Order_Status__c = 'Active',
            Quote__c = existing.Quote__c
        );

        try {
            insert duplicate;
            System.assert(false, 'Expected duplicate installation insert to fail.');
        } catch (DmlException ex) {
            System.assert(ex.getMessage().contains('Duplicate installation record'),
                'Duplicate error message should mention duplicate installation record.');
        }
    }

    @IsTest
    static void testHandleTerminatedInstallationsCreatesCreditNote() {
        TestDataFactory_OTG.OrderContext ctx =
            TestDataFactory_OTG.buildOrderContext('Americas', 'Amendment', 'Draft', true, false);

        Contract contractRec = [
            SELECT Id, CurrencyIsoCode
            FROM Contract
            WHERE Id = :ctx.packageRec.Contract__c
        ];
        update new Contract(
            Id = contractRec.Id,
            Status = 'Activated',
            StartDate = Date.today().addMonths(-2),
            EndDate = Date.today().addMonths(10),
            Billing_Frequency__c = 'Monthly'
        );

        Installation__c inst = [
            SELECT Id, Package__c, Quote__c
            FROM Installation__c
            WHERE Id = :ctx.installation.Id
        ];

        update new Installation__c(
            Id = inst.Id,
            Installation_Order_Status__c = 'Active',
            Contract__c = contractRec.Id,
            Installation_Start_Date__c = Date.today().addMonths(-1),
            Installation_End_Date__c = Date.today().addMonths(11),
            CurrencyIsoCode = contractRec.CurrencyIsoCode
        );

        Installation_Line__c instLine = new Installation_Line__c(
            Name = 'Active Line',
            Installation__c = inst.Id,
            Start_Date__c = Date.today().addMonths(-1),
            End_Date__c = Date.today().addMonths(1),
            Net_Total__c = 900,
            CurrencyIsoCode = contractRec.CurrencyIsoCode
        );
        insert instLine;

        Sales_Order__c unbilledSO = new Sales_Order__c(
            Installation__c = inst.Id,
            Contract__c = contractRec.Id,
            Start_Date__c = Date.today().addDays(-5),
            End_Date__c = Date.today().addDays(35),
            Status__c = 'Pending Approval',
            CurrencyIsoCode = contractRec.CurrencyIsoCode
        );

        Sales_Order__c billedSO = new Sales_Order__c(
            Installation__c = inst.Id,
            Contract__c = contractRec.Id,
            Start_Date__c = Date.today().addDays(-15),
            End_Date__c = Date.today().addDays(15),
            Status__c = 'Billed',
            CurrencyIsoCode = contractRec.CurrencyIsoCode
        );
        insert new List<Sales_Order__c>{ unbilledSO, billedSO };

        insert new Sales_Order_Item__c(
            Sales_Order__c = billedSO.Id,
            Installation_Line__c = instLine.Id,
            Amount__c = 900,
            CurrencyIsoCode = contractRec.CurrencyIsoCode,
            Name = 'Primary Item'
        );

        Date terminationDate = Date.today();

        Test.startTest();
        InstallationTriggerHandler.handleTerminatedInstallations(
            new List<Id>{ inst.Id },
            terminationDate
        );
        Test.stopTest();

        Sales_Order__c refreshedUnbilled = [
            SELECT Status__c
            FROM Sales_Order__c
            WHERE Id = :unbilledSO.Id
        ];
        System.assertEquals('Cancelled', refreshedUnbilled.Status__c,
            'Unbilled sales order should be cancelled on termination.');

        List<Sales_Order__c> replacementOrders = [
            SELECT Id, Credit_Note__c, Start_Date__c, End_Date__c, Status__c, Original_Sales_Order__c
            FROM Sales_Order__c
            WHERE Installation__c = :inst.Id
                AND Credit_Note__c = false
                AND Original_Sales_Order__c = :unbilledSO.Id
        ];
        System.assertEquals(1, replacementOrders.size(), 'A truncated replacement order should be created.');
        System.assertEquals('Pending Approval', replacementOrders[0].Status__c,
            'Replacement order should remain in pending approval.');
        System.assertEquals(unbilledSO.Start_Date__c, replacementOrders[0].Start_Date__c,
            'Replacement order should keep the original start date.');
        System.assertEquals(terminationDate, replacementOrders[0].End_Date__c,
            'Replacement order should end on the termination date.');

        List<Sales_Order_Item__c> replacementItems = [
            SELECT Amount__c
            FROM Sales_Order_Item__c
            WHERE Sales_Order__c = :replacementOrders[0].Id
        ];
        System.assertEquals(1, replacementItems.size(), 'Replacement order should receive one prorated item.');
        Decimal expectedReplacementAmount = (
            instLine.Net_Total__c /
            (instLine.Start_Date__c.daysBetween(instLine.End_Date__c) + 1) *
            (unbilledSO.Start_Date__c.daysBetween(terminationDate) + 1)
        ).setScale(2);
        System.assertEquals(expectedReplacementAmount, replacementItems[0].Amount__c,
            'Replacement order item should include the termination date when prorating.');

        List<Sales_Order__c> creditOrders = [
            SELECT Id, Credit_Note__c, Start_Date__c, End_Date__c, Status__c
            FROM Sales_Order__c
            WHERE Installation__c = :inst.Id AND Credit_Note__c = true
        ];
        System.assertEquals(1, creditOrders.size(), 'Exactly one credit note should be created.');
        System.assertEquals('Pending Approval', creditOrders[0].Status__c, 'Credit note should be unbilled.');
        System.assertEquals(terminationDate, creditOrders[0].Start_Date__c,
            'Credit note should start on termination date.');

        List<Sales_Order_Item__c> creditItems = [
            SELECT Amount__c
            FROM Sales_Order_Item__c
            WHERE Sales_Order__c = :creditOrders[0].Id
        ];
        System.assertEquals(1, creditItems.size(), 'Credit note should receive one item.');
        System.assert(creditItems[0].Amount__c < 0, 'Credit note item should refund (negative amount).');
    }

    @IsTest
    static void testAfterUpdateFutureTerminatedOnlyUpdatesStatus() {
        TestDataFactory_OTG.OrderContext ctx =
            TestDataFactory_OTG.buildOrderContext('Americas', 'Amendment', 'Draft', true, false);

        Contract contractRec = [
            SELECT Id
            FROM Contract
            WHERE Id = :ctx.packageRec.Contract__c
        ];

        Date contractStart = Date.today().addDays(-30);
        Date contractEnd = Date.today().addDays(90);
        update new Contract(
            Id = contractRec.Id,
            Status = 'Activated',
            StartDate = contractStart,
            EndDate = contractEnd,
            Billing_Frequency__c = 'Monthly'
        );

        Installation__c inst = [
            SELECT Id, Contract__c, Package__c
            FROM Installation__c
            WHERE Id = :ctx.installation.Id
        ];

        Date terminationDate = Date.today().addDays(10);

        Test.startTest();
        update new Installation__c(
            Id = inst.Id,
            Contract__c = contractRec.Id,
            Package__c = inst.Package__c,
            Installation_Order_Status__c = 'Future Terminated',
            Termination_End_Date__c = terminationDate,
            Termination_Reason__c = 'Scheduled'
        );
        Test.stopTest();

        Installation__c refreshed = [
            SELECT Installation_Order_Status__c, Auto_Installation_Termination_Error__c
            FROM Installation__c
            WHERE Id = :inst.Id
        ];
        System.assertEquals('Future Terminated', refreshed.Installation_Order_Status__c,
            'Future termination should only update the installation status.');
        System.assertEquals(null, refreshed.Auto_Installation_Termination_Error__c,
            'Future termination should not invoke amendment processing from the trigger.');
    }
}