force-app/main/default/objects/Contract/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Installation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_End_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_End_date__c</fullName>
    <label>Installation End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Start_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_date__c</fullName>
    <label>Installation Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 3)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria.Please select Invoice Account</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Replica Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contract_Customer__c</field>
            <operation>equals</operation>
            <valueField>Account.B2B_Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Invoice account)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/Installation_Line__c.object-meta.xml
<CustomObject>
    <label>Installation Line</label>
    <nameField>
        <label>Installation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Line__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <formula>TEXT(Contract__r.Billing_Frequency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unbilled</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fulfilment</fullName>
            </value>
            <value>
                <fullName>Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Pending Billing/Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/Sales_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Item__c/fields/Installation_Line__c.field-meta.xml
<CustomField>
    <fullName>Installation_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Line</label>
    <referenceTo>Installation_Line__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesOrderGeneratorService.cls
public class SalesOrderGeneratorService {

    public static void generateSalesOrders(List<Installation__c> installations, Boolean isRenewal, Boolean isPackageChange) {
        Savepoint sp = Database.setSavePoint();
        try {
            List<Installation__c> validInstallations = fetchInstallationsWithDetails(installations);
            if (validInstallations.isEmpty()) return;

            Map<Id, List<Installation_Line__c>> lineMap = fetchInstallationLinesGrouped(validInstallations);
            List<Sales_Order__c> salesOrders = new List<Sales_Order__c>();

            for (Installation__c inst : validInstallations) {
                List<Installation_Line__c> instLines = lineMap.get(inst.Id);
                if (instLines == null || instLines.isEmpty()) continue;

                Date instStart = isRenewal ? inst.Contract__r.StartDate : inst.Installation_Start_Date__c;
                Date instEnd = inst.Installation_End_Date__c;
                Date contractStart = inst.Contract__r.StartDate;
                
                // Order activation date (ActivatedDate -> EffectiveDate -> today)
                Date orderActivationDate;
                if (inst.Order__c != null && inst.Order__r.EffectiveDate != null) {
                    orderActivationDate = inst.Order__r.EffectiveDate;
                } else {
                    orderActivationDate = Date.today();
                }

                Integer interval = getBillingCycleMonths(inst.Contract__r.Billing_Frequency__c);
                
                // If package change, anchor BOTH contractStart & installStart to the Order activation date
                Date anchorContractStart = contractStart;
                Date anchorInstallStart  = isPackageChange ? orderActivationDate : instStart;

                List<BillingPeriod> billingPeriods =
                    generateBillingPeriods(anchorContractStart, instEnd, interval, anchorInstallStart);

                for (Integer i = 0; i < billingPeriods.size(); i++) {
                    Date periodStart = billingPeriods[i].startDate;
                    Date periodEnd = billingPeriods[i].endDate;

                    if (periodEnd < anchorInstallStart) continue;
                    if (periodStart > instEnd) continue;

                    if (periodStart < anchorInstallStart && anchorInstallStart <= periodEnd) {
                        periodStart = anchorInstallStart;
                    }

                    if (periodEnd > instEnd) periodEnd = instEnd;

                    salesOrders.add(new Sales_Order__c(
                        Contract__c = inst.Contract__c,
                        Invoice_Account__c = inst.Invoice_Account__c,
                        Installation__c = inst.Id,
                        Start_Date__c = periodStart,
                        End_Date__c = periodEnd,
                        Status__c = 'Pending Approval',
                        CurrencyIsoCode = inst.Contract__r.CurrencyIsoCode
                    ));
                }
            }

            insert salesOrders;
            Logger.info('Inserted Sales Orders: ' + salesOrders.size());
            Logger.saveLog();

            createSalesOrderItems(salesOrders, lineMap);

        } catch (Exception ex) {
            Database.rollback(sp);
            Logger.error('Sales Order generation failed: ' + ex.getMessage() + '\n' + ex.getStackTraceString());
            Logger.saveLog();
            throw new AuraHandledException('Sales Order creation failed: ' + ex.getMessage());
        }
    }

    private static List<Installation__c> fetchInstallationsWithDetails(List<Installation__c> installations) {
        return [
            SELECT Id, Contract__c, Invoice_Account__c, CurrencyIsoCode,
                   Installation_Start_Date__c, Installation_End_Date__c,
                   Contract__r.Billing_Frequency__c, Contract__r.StartDate,Contract__r.CurrencyIsoCode,
                   Order__c,Order__r.ActivatedDate,Order__r.EffectiveDate
            FROM Installation__c
            WHERE Id IN :installations
        ];
    }

    private static Map<Id, List<Installation_Line__c>> fetchInstallationLinesGrouped(List<Installation__c> installations) {
        Map<Id, List<Installation_Line__c>> lineMap = new Map<Id, List<Installation_Line__c>>();
        Set<Id> instIds = new Set<Id>();
        for (Installation__c inst : installations) instIds.add(inst.Id);

        List<Installation_Line__c> lines = [
            SELECT Id, Name, Installation__c, Subscription__c, Quote_Line__c,
                   Product__c, CurrencyIsoCode, Net_Total__c, Start_Date__c, End_Date__c
            FROM Installation_Line__c
            WHERE Installation__c IN :instIds AND End_Date__c > :Date.today()
        ];

        for (Installation_Line__c line : lines) {
            if (!lineMap.containsKey(line.Installation__c)) {
                lineMap.put(line.Installation__c, new List<Installation_Line__c>());
            }
            lineMap.get(line.Installation__c).add(line);
        }

        return lineMap;
    }

    private static void createSalesOrderItems(List<Sales_Order__c> salesOrders, Map<Id, List<Installation_Line__c>> lineMap) {
        List<Sales_Order_Item__c> soiToInsert = new List<Sales_Order_Item__c>();

        for (Sales_Order__c so : salesOrders) {
            List<Installation_Line__c> lines = lineMap.get(so.Installation__c);
            if (lines == null) continue;

            for (Installation_Line__c line : lines) {
                if (line.Start_Date__c <= so.End_Date__c && line.End_Date__c >= so.Start_Date__c) {
                    Double amount = calculateProratedAmount(line, so);
                    soiToInsert.add(new Sales_Order_Item__c(
                        Name = line.Name,
                        Sales_Order__c = so.Id,
                        Installation_Line__c = line.Id,
                        Subscription__c = line.Subscription__c,
                        CurrencyIsoCode = line.CurrencyIsoCode,
                        Amount__c = amount
                    ));
                }
            }
        }

        if (!soiToInsert.isEmpty()) {
            InstallationTriggerHandler.byPassSOcreation = true;
            insert soiToInsert;
            Logger.info('Inserted Sales Order Items: ' + soiToInsert.size());
            Logger.saveLog();
        }
    }

    @TestVisible
    private static List<BillingPeriod> generateBillingPeriods(Date contractStart, Date contractEnd, Integer interval, Date installStart) {
    List<BillingPeriod> periods = new List<BillingPeriod>();

    // Step 1: Find the first aligned billing period based on contract start
    Date firstAlignedStart = contractStart;
    while (firstAlignedStart.addMonths(interval) <= installStart) {
        firstAlignedStart = firstAlignedStart.addMonths(interval);
    }

    // Step 2: Calculate first billing period end
    Date firstPeriodEnd = getAccuratePeriodEnd(firstAlignedStart, interval);
    if (firstPeriodEnd > contractEnd) {
        firstPeriodEnd = contractEnd;
    }

    // Step 3: First billing period (from installStart to aligned period end)
    periods.add(new BillingPeriod(installStart, firstPeriodEnd));

    // Step 4: Remaining billing periods
    Date periodStart = firstPeriodEnd.addDays(1);
    while (periodStart <= contractEnd) {
        Date periodEnd = getAccuratePeriodEnd(periodStart, interval);
        if (periodEnd > contractEnd) {
            periodEnd = contractEnd;
        }
        periods.add(new BillingPeriod(periodStart, periodEnd));
        periodStart = periodEnd.addDays(1);
    }

    return periods;
}
    
    @TestVisible
    private static Date getAccuratePeriodEnd(Date startDate, Integer interval) {
    // Try adding interval months
    Date tentativeEnd = startDate.addMonths(interval);

    // If adding months skips to a shorter month (e.g., Feb), backtrack to last day of previous month
    if (startDate.day() > 28 && tentativeEnd.day() < startDate.day()) {
        Integer year = tentativeEnd.year();
        Integer month = tentativeEnd.month();

        // Get last day of the month
        Date monthEnd = Date.newInstance(year, month + 1, 1).addDays(-1);
        return monthEnd;
    }

    return tentativeEnd.addDays(-1);
}
    
    public static Double calculateProratedAmount(Installation_Line__c line, Sales_Order__c so) {
        try {
            if (line.Start_Date__c.day() == line.End_Date__c.addDays(1).day() &&
                so.Start_Date__c.day() == so.End_Date__c.addDays(1).day()) {
                Double totalMonths = (Double) line.Start_Date__c.monthsBetween(line.End_Date__c.addDays(1));
                Double soMonths = (Double) so.Start_Date__c.monthsBetween(so.End_Date__c.addDays(1));
                return (soMonths / totalMonths) * line.Net_Total__c;
            } else {
                Double totalDays = (Double) line.Start_Date__c.daysBetween(line.End_Date__c) + 1;
                Double soDays = (Double) so.Start_Date__c.daysBetween(so.End_Date__c) + 1;
                return (soDays / totalDays) * line.Net_Total__c;
            }
        } catch (Exception ex) {
            Logger.error('Error in calculateProratedAmount: ' + ex.getMessage() + '\n' + ex.getStackTraceString());
            Logger.saveLog();
            return 0;
        }
    }

    @TestVisible
    private static Integer getBillingCycleMonths(String billingFrequency) {
        if (billingFrequency == 'Monthly') return 1;
        if (billingFrequency == 'Quarterly') return 3;
        if (billingFrequency == 'Semiannual') return 6;
        if (billingFrequency == 'Annual') return 12;
        return 12;
    }

    public class BillingPeriod {
        public Date startDate;
        public Date endDate;

        public BillingPeriod(Date startDate, Date endDate) {
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
}