force-app/main/default/objects/Contract/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Installation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_End_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_End_date__c</fullName>
    <label>Installation End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Order_Status__c</fullName>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Implementation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Future Terminated</fullName>
            </value>
            <value>
                <fullName>Termination Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Start_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_date__c</fullName>
    <label>Installation Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 3)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria.Please select Invoice Account</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Replica Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contract_Customer__c</field>
            <operation>equals</operation>
            <valueField>Account.B2B_Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Invoice account)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Package__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contract_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/Installation_Line__c.object-meta.xml
<CustomObject>
    <label>Installation Line</label>
    <nameField>
        <label>Installation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Line__c/fields/Change_Action__c.field-meta.xml
<CustomField>
    <fullName>Change_Action__c</fullName>
    <label>Change Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Add Product</fullName>
            </value>
            <value>
                <fullName>Remove Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Implementation_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Completed_Date__c</fullName>
    <label>Implementation Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Implementation_Status__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Status__c</fullName>
    <label>Implementation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Implementation</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Source_Service_Order__c.field-meta.xml
<CustomField>
    <fullName>Source_Service_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Service Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Service Order Installation Lines</relationshipLabel>
    <relationshipName>Service_Order_Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Source_Subscription_Order__c.field-meta.xml
<CustomField>
    <fullName>Source_Subscription_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Subscription Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Subscription Order Installation Lines</relationshipLabel>
    <relationshipName>Subscription_Order_Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Service_Implementation_Completed__c.field-meta.xml
<CustomField>
    <fullName>Service_Implementation_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Implementation Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Addendum_Requires_SOW__c.field-meta.xml
<CustomField>
    <fullName>Addendum_Requires_SOW__c</fullName>
    <label>Addendum Requires SOW?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <formula>TEXT(Contract__r.Billing_Frequency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unbilled</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fulfilment</fullName>
            </value>
            <value>
                <fullName>Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Pending Billing/Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/Sales_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Item__c/fields/Installation_Line__c.field-meta.xml
<CustomField>
    <fullName>Installation_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Line</label>
    <referenceTo>Installation_Line__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Requires_Service_Order__c.field-meta.xml
<CustomField>
    <fullName>Requires_Service_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Service Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ServiceOrderImplementationControllerTest.cls
@IsTest
private class ServiceOrderImplementationControllerTest {
    @TestSetup
    static void setupData() {
        TestDataFactory_OTG.enableOrgVRConfig();
        TestDataFactory_OTG.primeDefaultOwnerAllRegions(UserInfo.getUserId());

        TestDataFactory_OTG.OrderContext ctx =
            TestDataFactory_OTG.buildOrderContext('Americas', 'Amendment', 'Draft', false, false);

        Contract contractRec = [
            SELECT Id, CurrencyIsoCode
            FROM Contract
            WHERE Id = :ctx.packageRec.Contract__c
            LIMIT 1
        ];
        Account invoiceAccount = TestDataFactory_OTG.createInvoiceAccount(
            UserInfo.getUserId(),
            TestDataFactory_OTG.getOrCreateCountryMappingId('Americas'),
            ctx.qctx.b2bAccount.Id
        );
        update new Contract(
            Id = contractRec.Id,
            Status = 'Activated',
            StartDate = Date.today().addMonths(-1),
            EndDate = Date.today().addMonths(11),
            Billing_Frequency__c = 'Monthly'
        );
        update new SBQQ__Quote__c(
            Id = ctx.qctx.quote.Id,
            SBQQ__MasterContract__c = contractRec.Id,
            Requires_Service_Order__c = true
        );
        update new Product2(
            Id = ctx.qctx.product.Id,
            Addendum_Requires_SOW__c = 'Yes'
        );
        update new Order(
            Id = ctx.orderRec.Id,
            Status = 'Activated',
            Is_Activated__c = true
        );
        update new Package__c(
            Id = ctx.packageRec.Id,
            Product_Change_Type__c = 'New Product Added'
        );
        update new Installation__c(
            Id = ctx.installation.Id,
            Contract__c = contractRec.Id,
            Order__c = ctx.orderRec.Id,
            Installation_Order_Status__c = 'Active',
            Installation_Start_Date__c = Date.today(),
            Installation_End_Date__c = Date.today().addMonths(6)
        );

        Order serviceOrder = new Order(
            OpportunityId = ctx.qctx.opportunity.Id,
            Type = 'Service Delivery',
            Status = 'Draft',
            EffectiveDate = Date.today(),
            Pricebook2Id = TestDataFactory_OTG.getStandardPricebookIdCached(),
            Subscription_Order__c = ctx.orderRec.Id
        );
        insert serviceOrder;
        TestDataFactory_OTG.addOrderItem(serviceOrder.Id, ctx.qctx.pbe.Id, 100, 1);

        Installation_Line__c pendingLine = new Installation_Line__c(
            Name = 'Implementation Product',
            Installation__c = ctx.installation.Id,
            Product__c = ctx.qctx.product.Id,
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addMonths(6),
            Net_Total__c = 120,
            CurrencyIsoCode = contractRec.CurrencyIsoCode,
            Implementation_Status__c = 'Pending Implementation',
            Change_Action__c = 'Add Product',
            Source_Subscription_Order__c = ctx.orderRec.Id
        );
        insert pendingLine;

        Product2 noSowProduct = new Product2(
            Name = 'No SOW Product',
            IsActive = true,
            Addendum_Requires_SOW__c = 'No'
        );
        insert noSowProduct;

        insert new Installation_Line__c(
            Name = 'No SOW Implementation Product',
            Installation__c = ctx.installation.Id,
            Product__c = noSowProduct.Id,
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addMonths(6),
            Net_Total__c = 80,
            CurrencyIsoCode = contractRec.CurrencyIsoCode,
            Implementation_Status__c = 'Pending Implementation',
            Change_Action__c = 'Add Product',
            Source_Subscription_Order__c = ctx.orderRec.Id
        );

        insert new Sales_Order__c(
            Contract__c = contractRec.Id,
            Installation__c = ctx.installation.Id,
            Invoice_Account__c = invoiceAccount.Id,
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addMonths(1).addDays(-1),
            Status__c = 'Pending Approval',
            CurrencyIsoCode = contractRec.CurrencyIsoCode
        );
    }

    @IsTest
    static void testGetAndCompleteSelectedLines() {
        Order serviceOrder = [
            SELECT Id
            FROM Order
            WHERE Type = 'Service Delivery'
            LIMIT 1
        ];

        ServiceOrderImplementationController.WorkResponse initialResponse =
            ServiceOrderImplementationController.getImplementationWork(serviceOrder.Id);
        System.assertEquals(1, initialResponse.packages.size(), 'One package should be returned.');
        System.assertEquals(1, initialResponse.installations.size(), 'One installation should be returned.');
        System.assertEquals(1, initialResponse.installations[0].lines.size(), 'Only SOW-required products should be returned.');

        Id lineId = initialResponse.installations[0].lines[0].lineId;

        Test.startTest();
        ServiceOrderImplementationController.WorkResponse completedResponse =
            ServiceOrderImplementationController.completeLines(serviceOrder.Id, new List<Id>{ lineId });
        Test.stopTest();

        System.assertEquals('Completed', completedResponse.installations[0].lines[0].status);
        Installation_Line__c completedLine = [
            SELECT Implementation_Status__c, Implementation_Completed_Date__c, Source_Service_Order__c
            FROM Installation_Line__c
            WHERE Id = :lineId
        ];
        System.assertEquals('Completed', completedLine.Implementation_Status__c);
        System.assertEquals(Date.today(), completedLine.Implementation_Completed_Date__c);
        System.assertEquals(serviceOrder.Id, completedLine.Source_Service_Order__c);
        System.assertEquals(1, [SELECT COUNT() FROM Sales_Order_Item__c WHERE Installation_Line__c = :lineId]);
    }

    @IsTest
    static void testCompletePackageAndServiceOrder() {
        Order serviceOrder = [
            SELECT Id
            FROM Order
            WHERE Type = 'Service Delivery'
            LIMIT 1
        ];
        Package__c pkg = [
            SELECT Id
            FROM Package__c
            WHERE Product_Change_Type__c = 'New Product Added'
            LIMIT 1
        ];

        Test.startTest();
        ServiceOrderImplementationController.completePackage(serviceOrder.Id, pkg.Id);
        ServiceOrderImplementationController.WorkResponse response =
            ServiceOrderImplementationController.completeServiceOrder(serviceOrder.Id);
        Test.stopTest();

        System.assertEquals(true, response.orderSummary.serviceImplementationCompleted);
        Order refreshedServiceOrder = [
            SELECT Service_Implementation_Completed__c
            FROM Order
            WHERE Id = :serviceOrder.Id
        ];
        System.assertEquals(true, refreshedServiceOrder.Service_Implementation_Completed__c);
    }

    @IsTest
    static void testCompleteInstallationUsesSelectedCompletionDate() {
        Order serviceOrder = [
            SELECT Id
            FROM Order
            WHERE Type = 'Service Delivery'
            LIMIT 1
        ];
        Installation_Line__c pendingLine = [
            SELECT Id, Installation__c
            FROM Installation_Line__c
            WHERE Implementation_Status__c = 'Pending Implementation'
            LIMIT 1
        ];
        Date selectedCompletionDate = Date.today().addDays(-7);

        Test.startTest();
        ServiceOrderImplementationController.completeInstallationWithDate(
            serviceOrder.Id,
            pendingLine.Installation__c,
            selectedCompletionDate
        );
        Test.stopTest();

        Installation_Line__c completedLine = [
            SELECT Implementation_Status__c, Implementation_Completed_Date__c, Source_Service_Order__c
            FROM Installation_Line__c
            WHERE Id = :pendingLine.Id
        ];
        System.assertEquals('Completed', completedLine.Implementation_Status__c);
        System.assertEquals(selectedCompletionDate, completedLine.Implementation_Completed_Date__c);
        System.assertEquals(serviceOrder.Id, completedLine.Source_Service_Order__c);
    }

    @IsTest
    static void testCompleteInstallationRejectsDateOutsideContractPeriod() {
        Order serviceOrder = [
            SELECT Id, Subscription_Order__r.SBQQ__Quote__r.SBQQ__MasterContract__r.StartDate
            FROM Order
            WHERE Type = 'Service Delivery'
            LIMIT 1
        ];
        Installation_Line__c pendingLine = [
            SELECT Id, Installation__c
            FROM Installation_Line__c
            WHERE Implementation_Status__c = 'Pending Implementation'
            LIMIT 1
        ];
        Date invalidCompletionDate =
            serviceOrder.Subscription_Order__r.SBQQ__Quote__r.SBQQ__MasterContract__r.StartDate.addDays(-1);

        try {
            ServiceOrderImplementationController.completeInstallationWithDate(
                serviceOrder.Id,
                pendingLine.Installation__c,
                invalidCompletionDate
            );
            System.assert(false, 'Expected validation error when completion date is before the contract start date.');
        } catch (AuraHandledException ex) {
            System.assertNotEquals(null, ex, 'Expected AuraHandledException for invalid completion date.');
        }
    }

    @IsTest
    static void testGetImplementationWorkRequiresActivatedSubscriptionOrder() {
        Order serviceOrder = [
            SELECT Id, Subscription_Order__c, Subscription_Order__r.SBQQ__Quote__c
            FROM Order
            WHERE Type = 'Service Delivery'
            LIMIT 1
        ];
        update new SBQQ__Quote__c(
            Id = serviceOrder.Subscription_Order__r.SBQQ__Quote__c,
            SBQQ__Type__c = 'Amendment',
            Requires_Service_Order__c = true
        );
        update new Order(
            Id = serviceOrder.Subscription_Order__c,
            Status = 'Draft',
            Is_Activated__c = false
        );

        try {
            ServiceOrderImplementationController.getImplementationWork(serviceOrder.Id);
            System.assert(false, 'Expected validation error when opening implementation for inactive subscription order.');
        } catch (AuraHandledException ex) {
            System.assertNotEquals(null, ex, 'Expected AuraHandledException for inactive subscription order.');
        }
    }

    @IsTest
    static void testCompleteLinesRequiresActivatedSubscriptionOrder() {
        Order serviceOrder = [
            SELECT Id, Subscription_Order__c, Subscription_Order__r.SBQQ__Quote__c
            FROM Order
            WHERE Type = 'Service Delivery'
            LIMIT 1
        ];
        update new SBQQ__Quote__c(
            Id = serviceOrder.Subscription_Order__r.SBQQ__Quote__c,
            SBQQ__Type__c = 'Amendment',
            Requires_Service_Order__c = true
        );
        update new Order(
            Id = serviceOrder.Subscription_Order__c,
            Status = 'Draft',
            Is_Activated__c = false
        );
        Id lineId = [
            SELECT Id
            FROM Installation_Line__c
            WHERE Implementation_Status__c = 'Pending Implementation'
            LIMIT 1
        ].Id;

        try {
            ServiceOrderImplementationController.completeLines(serviceOrder.Id, new List<Id>{ lineId });
            System.assert(false, 'Expected validation error when subscription order is not activated.');
        } catch (AuraHandledException ex) {
            System.assertNotEquals(null, ex, 'Expected AuraHandledException for inactive subscription order.');
        }
    }
}