force-app/main/default/objects/Contract/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Migrated_Contract__c.field-meta.xml
<CustomField>
    <fullName>Migrated_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migrated Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Installation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Auto_Installation__c.field-meta.xml
<CustomField>
    <fullName>Auto_Installation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Installation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Auto_Termination__c.field-meta.xml
<CustomField>
    <fullName>Auto_Termination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Termination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_End_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_End_date__c</fullName>
    <label>Installation End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Order_Status__c</fullName>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Implementation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Future Terminated</fullName>
            </value>
            <value>
                <fullName>Termination Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Start_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_date__c</fullName>
    <label>Installation Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 3)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria.Please select Invoice Account</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Replica Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contract_Customer__c</field>
            <operation>equals</operation>
            <valueField>Account.B2B_Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Invoice account)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/Installation_Line__c.object-meta.xml
<CustomObject>
    <label>Installation Line</label>
    <nameField>
        <label>Installation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Line__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <formula>TEXT(Contract__r.Billing_Frequency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unbilled</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fulfilment</fullName>
            </value>
            <value>
                <fullName>Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Pending Billing/Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/Sales_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Item__c/fields/Installation_Line__c.field-meta.xml
<CustomField>
    <fullName>Installation_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Line</label>
    <referenceTo>Installation_Line__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateSalesOrderService.cls
public class CreateSalesOrderService {
	public static void createSORecords(List<Installation__c> installations) {
		try {
			List<Installation__c> newInstList = [
				SELECT
					Id,
					Name,
					Invoice_Account__c,
					Auto_Installation__c,
					Auto_Termination__c,
					CurrencyIsoCode,
                	Quote__r.SBQQ__Type__c,
					Contract__r.SBQQ__Quote__r.SBQQ__Type__c,
					Contract__r.Migrated_Contract__c,
					Contract__r.StartDate,
					Contract__r.EndDate,
					Installation_Start_date__c,
					Installation_End_date__c,
					Contract__c,
					Contract__r.Billing_Frequency__c,
					Contract__r.ContractTerm
				FROM Installation__c
				WHERE Id IN :installations AND Installation_Order_Status__c = 'Active'
			];
            System.debug('inst list--> ' + newInstList);
			List<Sales_Order__c> salesOrdersToCreate = new List<Sales_Order__c>();
			Set<Date> startDateSet = new Set<Date>();
			Set<Date> endDateSet = new Set<Date>();

			Date earliestStartDate = Date.today();
			Date latestEndDate = Date.today();
            
            System.debug('newInstList --> ' + newInstList);

			for (Installation__c installation : newInstList) {
				Integer billingCycleMonths = getBillingCycleMonths(installation.Contract__r.Billing_Frequency__c);
				Integer contractTerm = installation.Auto_Installation__c
					? installation.Installation_Start_date__c.monthsBetween(installation.Installation_End_date__c)
					: installation.Contract__r.ContractTerm;
                
				for (Integer i = 0; i < (Math.ceil((Decimal) contractTerm/billingCycleMonths)); i++) {
					Date salesOrderStartDate = installation.Installation_Start_date__c.addMonths(i * billingCycleMonths);
					if (installation.Contract__r.Migrated_Contract__c && (installation.Quote__c == NULL || installation.Quote__r.SBQQ__Type__c != 'Amendment')) {
						salesOrderStartDate = installation.Contract__r.StartDate.addMonths(i * billingCycleMonths);
					}
                    if (installation.Quote__r.SBQQ__Type__c == 'Renewal') {
						salesOrderStartDate = installation.Contract__r.StartDate.addMonths(i * billingCycleMonths);
					}
					
					Date salesOrderEndDate = salesOrderStartDate.addMonths(billingCycleMonths).addDays(-1);
					Date instEndDate = installation.Installation_End_date__c == null
						? installation.Contract__r.EndDate
						: installation.Installation_End_date__c;

					Sales_Order__c salesOrder = new Sales_Order__c(
						Contract__c = installation.Contract__c,
						Invoice_Account__c = installation.Invoice_Account__c,
						Installation__c = installation.Id,
						Start_Date__c = salesOrderStartDate,
						End_Date__c = salesOrderEndDate > instEndDate ? instEndDate : salesOrderEndDate,
						Status__c = 'Unbilled',
						CurrencyIsoCode = installation.CurrencyIsoCode
					);
                    System.debug('salesOrder --> ' + salesOrder);

					salesOrdersToCreate.add(salesOrder);
					startDateSet.add(salesOrderStartDate);
					endDateSet.add(salesOrderEndDate);
					earliestStartDate = earliestStartDate > salesOrderStartDate ? salesOrderStartDate : earliestStartDate;
					latestEndDate = latestEndDate < salesOrderEndDate ? salesOrderEndDate : latestEndDate;
				}
			}
            System.debug('salesOrdersToCreate --> ' + salesOrdersToCreate);

			if (!salesOrdersToCreate.isEmpty()) {
				insert salesOrdersToCreate;
			}
			createSOIRecords(installations, salesOrdersToCreate, earliestStartDate, latestEndDate);
		} catch (Exception ex) {
            System.debug(ex.getMessage() + '\n\n' + ex.getLineNumber() + '\n\n' + ex.getStackTraceString());
			Logger.error(ex.getMessage() + '\n\n' + ex.getLineNumber() + '\n\n' + ex.getStackTraceString());
			Logger.saveLog();
		}
	}

	public static void createSOIRecords(
		List<Installation__c> installations,
		List<Sales_Order__c> soList,
		Date earliestStartDate,
		Date latestEndDate
	) {
		try {
			List<Id> instIdList = new List<Id>();
			for (Installation__c inst : installations) {
				instIdList.add(inst.Id);
			}
			System.debug('instIdList --> ' + instIdList);
			System.debug('earliestStartDate --> ' + earliestStartDate);
			System.debug('latestEndDate --> ' + latestEndDate);
			List<Installation_Line__c> installationLines = [
				SELECT
					Id,
					Name,
					Installation__c,
					Product__c,
					Quote_Line__c,
					CurrencyIsoCode,
					Net_Total__c,
					Subscription__c,
					Start_Date__c,
					End_Date__c
				FROM Installation_Line__c
				WHERE Installation__c IN :instIdList AND Start_Date__c >= :earliestStartDate AND End_Date__c <= :latestEndDate
			];

			System.debug('installationLines --> ' + installationLines);

			Map<Id, List<Installation_Line__c>> installationLineMap = new Map<Id, List<Installation_Line__c>>();
			for (Installation_Line__c line : installationLines) {
				if (!installationLineMap.containsKey(line.Installation__c)) {
					installationLineMap.put(line.Installation__c, new List<Installation_Line__c>());
				}
				installationLineMap.get(line.Installation__c).add(line);
			}
			System.debug('installationLineMap --> ' + installationLineMap);
			List<Sales_Order_Item__c> salesOrderItemsToCreate = new List<Sales_Order_Item__c>();
			for (Sales_Order__c salesOrder : soList) {
				List<Installation_Line__c> relatedLines = installationLineMap.get(salesOrder.Installation__c);
				if (relatedLines != null && !relatedLines.isEmpty()) {
					for (Installation_Line__c line : relatedLines) {
						System.debug('line ' + line.Start_Date__c + '---' + line.End_Date__c);
						System.debug('so ' + salesOrder.Start_Date__c + '---' + salesOrder.End_Date__c);
                        System.debug('check --> ' + (line.Start_Date__c <= salesOrder.Start_Date__c && line.End_Date__c >= salesOrder.End_Date__c));
						if (line.Start_Date__c <= salesOrder.Start_Date__c && line.End_Date__c >= salesOrder.End_Date__c) {
							Double proratedAmount = calculateProratedAmount(line, salesOrder);
							System.debug('in if');
							Sales_Order_Item__c salesOrderItem = new Sales_Order_Item__c(
								Name = line.Name,
								Sales_Order__c = salesOrder.Id,
								Installation_Line__c = line.Id,
								Subscription__c = line.Subscription__c,
								CurrencyIsoCode = line.CurrencyIsoCode,
								Amount__c = proratedAmount
							);
							salesOrderItemsToCreate.add(salesOrderItem);
						}
					}
				}
			}

			if (!salesOrderItemsToCreate.isEmpty()) {
				InstallationTriggerHandler.byPassSOcreation = true;
				insert salesOrderItemsToCreate;
			}
		} catch (Exception ex) {
			Logger.error(ex.getMessage() + '\n\n' + ex.getLineNumber() + '\n\n' + ex.getStackTraceString());
			Logger.saveLog();
		}
	}

	@TestVisible
	private static Integer getBillingCycleMonths(String billingFrequency) {
		if (billingFrequency == 'Annual') {
			return 12;
		} else if (billingFrequency == 'Semiannual') {
			return 6;
		} else if (billingFrequency == 'Quarterly') {
			return 3;
		} else if (billingFrequency == 'Monthly') {
			return 1;
		} else {
			return 12; // Default to monthly if frequency is unknown
		}
	}

	public static Double calculateProratedAmount(Installation_Line__c line, Sales_Order__c salesOrder) {
    Double proratedAmount = 0;
    try {
        if (
            line.Start_Date__c.day() == line.End_Date__c.addDays(1).day() &&
            salesOrder.Start_Date__c.day() == salesOrder.End_Date__c.addDays(1).day()
        ) {
            // Full-month aligned → use month-based proration
            Double totalMonths = (Double) line.Start_Date__c.monthsBetween(line.End_Date__c.addDays(1));
            Double soMonths = (Double) salesOrder.Start_Date__c.monthsBetween(salesOrder.End_Date__c.addDays(1));
            proratedAmount = (soMonths / totalMonths) * line.Net_Total__c;
        } else {
            // Not aligned → use day-based proration
            Double totalDays = (Double) line.Start_Date__c.daysBetween(line.End_Date__c) + 1;
            Double soDays = (Double) salesOrder.Start_Date__c.daysBetween(salesOrder.End_Date__c) + 1;
            proratedAmount = (soDays / totalDays) * line.Net_Total__c;
        }
    } catch (Exception ex) {
        Logger.error('Error in calculateProratedAmount: ' + ex.getMessage() + '\n' + ex.getStackTraceString());
        Logger.saveLog();
    }
    return proratedAmount;
}
}