force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Installation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 3)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria.Please select Invoice Account</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Replica Invoice Account</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contract_Customer__c</field>
            <operation>equals</operation>
            <valueField>Account.B2B_Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Invoice account)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Line__c/Installation_Line__c.object-meta.xml
<CustomObject>
    <label>Installation Line</label>
    <nameField>
        <label>Installation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Line__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Installation Lines</relationshipLabel>
    <relationshipName>Installation_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Credit_Note__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credit Note</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>Installation__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Invoice_Account__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Original_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Original_Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Original Sales Orders</relationshipLabel>
    <relationshipName>Original_Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unbilled</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fulfilment</fullName>
            </value>
            <value>
                <fullName>Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Pending Billing/Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/Sales_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Item__c/fields/Installation_Line__c.field-meta.xml
<CustomField>
    <fullName>Installation_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Line</label>
    <referenceTo>Installation_Line__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Items</relationshipLabel>
    <relationshipName>Sales_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SalesOrderCloneControllerTest.cls
@IsTest
private class SalesOrderCloneControllerTest {
    @TestSetup
    static void setupOrgDefaults() {
        TestDataFactory_OTG.enableOrgVRConfig();
        TestDataFactory_OTG.primeDefaultOwnerAllRegions(UserInfo.getUserId());

        VRConfiguration__c config = VRConfiguration__c.getOrgDefaults();
        if (config == null) {
            config = new VRConfiguration__c();
        }
        upsert config;
    }

    @IsTest
    static void testCloneSalesOrderCreatesCloneAndChildItems() {
        TestDataFactory_OTG.OrderContext ctx =
            TestDataFactory_OTG.buildOrderContext('Americas', 'Amendment', 'Draft', true, false);

        Contract contractRec = [
            SELECT Id, CurrencyIsoCode
            FROM Contract
            WHERE Id = :ctx.packageRec.Contract__c
        ];

        Account invoiceAccount = new Account(Name = 'Clone Invoice Account');
        insert invoiceAccount;

        Sales_Order__c sourceOrder = new Sales_Order__c(
            Contract__c = contractRec.Id,
            Installation__c = ctx.installation.Id,
            Invoice_Account__c = invoiceAccount.Id,
            Start_Date__c = Date.today().addDays(-10),
            End_Date__c = Date.today().addDays(20),
            Comments__c = 'Original comments',
            Status__c = 'Billed',
            Credit_Note__c = true,
            CurrencyIsoCode = contractRec.CurrencyIsoCode
        );
        insert sourceOrder;

        Installation_Line__c installationLine = new Installation_Line__c(
            Name = 'Clone Line',
            Installation__c = ctx.installation.Id,
            Start_Date__c = Date.today().addDays(-10),
            End_Date__c = Date.today().addDays(20),
            Net_Total__c = 100,
            CurrencyIsoCode = contractRec.CurrencyIsoCode
        );
        insert installationLine;

        insert new List<Sales_Order_Item__c>{
            new Sales_Order_Item__c(
                Name = 'Clone Item 1',
                Sales_Order__c = sourceOrder.Id,
                Installation_Line__c = installationLine.Id,
                CurrencyIsoCode = contractRec.CurrencyIsoCode,
                Amount__c = 75
            ),
            new Sales_Order_Item__c(
                Name = 'Clone Item 2',
                Sales_Order__c = sourceOrder.Id,
                Installation_Line__c = installationLine.Id,
                CurrencyIsoCode = contractRec.CurrencyIsoCode,
                Amount__c = 25
            )
        };

        Test.startTest();
        Id cloneOrderId = SalesOrderCloneController.cloneSalesOrder(sourceOrder.Id);
        Test.stopTest();

        System.assertNotEquals(null, cloneOrderId, 'A cloned sales order should be created.');
        System.assertNotEquals(sourceOrder.Id, cloneOrderId, 'The clone must be a new record.');

        Sales_Order__c clonedOrder = [
            SELECT Contract__c, Installation__c, Invoice_Account__c, Start_Date__c, End_Date__c,
                   Comments__c, Status__c, Credit_Note__c, Original_Sales_Order__c, CurrencyIsoCode
            FROM Sales_Order__c
            WHERE Id = :cloneOrderId
        ];
        System.assertEquals(sourceOrder.Contract__c, clonedOrder.Contract__c, 'Contract should be copied.');
        System.assertEquals(sourceOrder.Installation__c, clonedOrder.Installation__c, 'Installation should be copied.');
        System.assertEquals(sourceOrder.Invoice_Account__c, clonedOrder.Invoice_Account__c, 'Invoice account should be copied.');
        System.assertEquals(sourceOrder.Start_Date__c, clonedOrder.Start_Date__c, 'Start date should be copied.');
        System.assertEquals(sourceOrder.End_Date__c, clonedOrder.End_Date__c, 'End date should be copied.');
        System.assertEquals(sourceOrder.Comments__c, clonedOrder.Comments__c, 'Comments should be copied.');
        System.assertEquals('Pending Approval', clonedOrder.Status__c, 'Cloned order should be pending approval.');
        System.assertEquals(false, clonedOrder.Credit_Note__c, 'Cloned order should not be a credit note.');
        System.assertEquals(sourceOrder.Id, clonedOrder.Original_Sales_Order__c, 'Clone should link to the source order.');

        List<Sales_Order_Item__c> clonedItems = [
            SELECT Name, Amount__c, Sales_Order__c, Installation_Line__c
            FROM Sales_Order_Item__c
            WHERE Sales_Order__c = :cloneOrderId
            ORDER BY Name
        ];
        System.assertEquals(2, clonedItems.size(), 'All source items should be cloned.');
        System.assertEquals('Clone Item 1', clonedItems[0].Name, 'First item should be copied.');
        System.assertEquals(75, clonedItems[0].Amount__c, 'First amount should be copied.');
        System.assertEquals('Clone Item 2', clonedItems[1].Name, 'Second item should be copied.');
        System.assertEquals(25, clonedItems[1].Amount__c, 'Second amount should be copied.');
    }

    @IsTest
    static void testCloneSalesOrderRequiresId() {
        try {
            SalesOrderCloneController.cloneSalesOrder(null);
            System.assert(false, 'Expected a validation error when no sales order id is provided.');
        } catch (AuraHandledException ex) {
            String message = ex.getMessage();
            System.assert(
                message.contains('Sales Order Id is required') || message.contains('Script-thrown exception'),
                'Expected the missing id validation to be raised.'
            );
        }
    }
}