force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Installation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Installation_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Order_Status__c</fullName>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Implementation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Future Terminated</fullName>
            </value>
            <value>
                <fullName>Termination Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Package__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contract_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Termination_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Termination_End_Date__c</fullName>
    <label>Termination End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Termination_Reason__c.field-meta.xml
<CustomField>
    <fullName>Termination_Reason__c</fullName>
    <inlineHelpText>Max 10000 characters</inlineHelpText>
    <label>Termination Reason</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Vessel_IMO__c.field-meta.xml
<CustomField>
    <fullName>Vessel_IMO__c</fullName>
    <formula>Vessel_Name__r.Vessel_IMO__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vessel IMO</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdatePackageController.cls
public with sharing class UpdatePackageController
{
    @AuraEnabled
    public static List<Package__c> fetchPackages(String qtId)
    {
        try
        {
            List<Package__c> packList = [SELECT Id, Name, Installation_Quantity__c, (SELECT Id, Name, Installation_Order_Status__c, Vessel_IMO__c FROM Installations__r WHERE Installation_Order_Status__c != 'Terminated') FROM Package__c WHERE Quote__c = :qtId];
            System.debug('packList --> ' + packList);
            return packList;
        }
        catch (Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static List<Package__c> getPackageData(String packId)
    {
        try
        {
            List<Package__c> packList = [SELECT Id, Name, Installation_Quantity__c, (SELECT Id, Name, Vessel_IMO__c, Installation_Order_Status__c FROM Installations__r WHERE Installation_Order_Status__c != 'Terminated') FROM Package__c WHERE Id = :packId];
            return packList;
        }
        catch (Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string saveInstallation(String packId, String instId, String swapInstId)
    {
        try
        {
            List<Installation__c> instList = new List<Installation__c>();
            Installation__c inst = new Installation__c(
                Id = instId,
                Package__c = packId
            );
            instList.add(inst);
            if(swapInstId != NULL && swapInstId != '')
            {
                instList.add(new Installation__c(
                    Id = swapInstId,
                    Installation_Order_Status__c = 'Terminated',
                    Termination_End_Date__c = Date.today(),
                    Termination_Reason__c = 'This has been terminated on Quote-Manage Installations.'
                ));
            }
            update instList;
            return 'SUCCESS';
        }
        catch (Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }
}