force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Installation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Change_Package_Status__c.field-meta.xml
<CustomField>
    <fullName>Change_Package_Status__c</fullName>
    <label>Change Package Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Order_Status__c</fullName>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Implementation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Future Terminated</fullName>
            </value>
            <value>
                <fullName>Termination Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Package__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contract_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Quote_Line_Group__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Group</label>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Change__c/Installation_Change__c.object-meta.xml
<CustomObject>
    <label>Installation Change</label>
    <pluralLabel>Installation Changes</pluralLabel>
    <nameField>
        <type>AutoNumber</type>
        <label>Installation Change Number</label>
        <displayFormat>IC-{000000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Change__c/fields/Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Change_Date__c</fullName>
    <label>Change Date</label>
    <type>DateTime</type>
    <defaultValue>NOW()</defaultValue>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/Change_Type__c.field-meta.xml
<CustomField>
    <fullName>Change_Type__c</fullName>
    <label>Change Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Package Change</fullName>
            </value>
            <value>
                <fullName>Product Change</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <type>Lookup</type>
    <referenceTo>Contract</referenceTo>
    <relationshipName>Installation_Changes_Contract</relationshipName>
    <relationshipLabel>Installation Changes (Contract)</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <label>Installation</label>
    <type>MasterDetail</type>
    <referenceTo>Installation__c</referenceTo>
    <relationshipName>Installation_Changes</relationshipName>
    <relationshipLabel>Installation Changes</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/New_Contract__c.field-meta.xml
<CustomField>
    <fullName>New_Contract__c</fullName>
    <label>New Contract</label>
    <type>Lookup</type>
    <referenceTo>Contract</referenceTo>
    <relationshipName>Installation_Changes_NewContract</relationshipName>
    <relationshipLabel>Installation Changes (New Contract)</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/New_Package__c.field-meta.xml
<CustomField>
    <fullName>New_Package__c</fullName>
    <label>New Package</label>
    <type>Lookup</type>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Installation_Changes_NewPackage</relationshipName>
    <relationshipLabel>Installation Changes (New Package)</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/New_Quote__c.field-meta.xml
<CustomField>
    <fullName>New_Quote__c</fullName>
    <label>New Quote</label>
    <type>Lookup</type>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipName>Installation_Changes_NewQuote</relationshipName>
    <relationshipLabel>Installation Changes (New Quote)</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/Old_Contract__c.field-meta.xml
<CustomField>
    <fullName>Old_Contract__c</fullName>
    <label>Old Contract</label>
    <type>Lookup</type>
    <referenceTo>Contract</referenceTo>
    <relationshipName>Installation_Changes_OldContract</relationshipName>
    <relationshipLabel>Installation Changes (Old Contract)</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/Old_Package__c.field-meta.xml
<CustomField>
    <fullName>Old_Package__c</fullName>
    <label>Old Package</label>
    <type>Lookup</type>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Installation_Changes_OldPackage</relationshipName>
    <relationshipLabel>Installation Changes (Old Package)</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/Old_Quote__c.field-meta.xml
<CustomField>
    <fullName>Old_Quote__c</fullName>
    <label>Old Quote</label>
    <type>Lookup</type>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipName>Installation_Changes_OldQuote</relationshipName>
    <relationshipLabel>Installation Changes (Old Quote)</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <type>Lookup</type>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Installation_Changes_Opportunity</relationshipName>
    <relationshipLabel>Installation Changes (Opportunity)</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <type>Lookup</type>
    <referenceTo>Order</referenceTo>
    <relationshipName>Installation_Changes_Order</relationshipName>
    <relationshipLabel>Installation Changes (Order)</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <type>Lookup</type>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Installation_Changes_Package</relationshipName>
    <relationshipLabel>Installation Changes (Package)</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <type>Lookup</type>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipName>Installation_Changes_Quote</relationshipName>
    <relationshipLabel>Installation Changes (Quote)</relationshipLabel>
</CustomField>

force-app/main/default/objects/Installation_Change__c/fields/Quote_Line_Group__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Group__c</fullName>
    <label>Quote Line Group</label>
    <type>Lookup</type>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipName>Installation_Changes_QLG</relationshipName>
    <relationshipLabel>Installation Changes (Quote Line Group)</relationshipLabel>
</CustomField>

force-app/main/default/classes/InstallationChangeService.cls
public class InstallationChangeService {
    public class ChangePayload {
        public Id installationId;
        public Id contractId;
        public Id quoteId;
        public Id opportunityId;
        public Id packageId;
        public Id quoteLineGroupId;
        public Id orderId;
        public String changeType;
        public Id oldPackageId;
        public Id newPackageId;
        public Id oldContractId;
        public Id newContractId;
        public Id oldQuoteId;
        public Id newQuoteId;
        public Boolean updateOrderOnly;
    }

    public static void enqueueChanges(List<Installation__c> newList, Map<Id, Installation__c> oldMap) {
        if (newList == null || newList.isEmpty() || oldMap == null || oldMap.isEmpty()) {
            return;
        }

        Set<Id> quoteIds = new Set<Id>();
        for (Installation__c inst : newList) {
            Installation__c oldInst = oldMap.get(inst.Id);
            if (oldInst == null) continue;

            if (inst.Quote__c != null) quoteIds.add(inst.Quote__c);
            if (oldInst.Quote__c != null) quoteIds.add(oldInst.Quote__c);
        }

        Map<Id, SBQQ__Quote__c> quoteMap = quoteIds.isEmpty() ? new Map<Id, SBQQ__Quote__c>() :
            new Map<Id, SBQQ__Quote__c>([
                SELECT Id, SBQQ__Opportunity2__c, SBQQ__Type__c
                FROM SBQQ__Quote__c
                WHERE Id IN :quoteIds
            ]);

        List<ChangePayload> payloads = new List<ChangePayload>();
        for (Installation__c inst : newList) {
            Installation__c oldInst = oldMap.get(inst.Id);
            if (oldInst == null) continue;
            Boolean isRenewalChange = isContractChange(oldInst, inst) && isRenewalQuote(inst, oldInst, quoteMap);
            Boolean isPackageChange = isPackageChangeInProgress(oldInst, inst);
            Boolean isPackageChangeCompleted = isPackageChangeCompletion(oldInst, inst);

            if (!isRenewalChange && isStatusChange(oldInst, inst, 'Active')) {
                payloads.add(buildPayload('Activated', inst, oldInst, quoteMap));
            }

            if (isRenewalChange) {
                ChangePayload renewalPayload = buildPayload('Renewal', inst, oldInst, quoteMap);
                renewalPayload.oldContractId = oldInst.Contract__c;
                renewalPayload.newContractId = inst.Contract__c;
                payloads.add(renewalPayload);
            }

            if (isPackageChange) {
                ChangePayload packagePayload = buildPayload('Package Change', inst, oldInst, quoteMap);
                packagePayload.oldPackageId = oldInst.Package__c;
                packagePayload.newPackageId = inst.Package__c;
                payloads.add(packagePayload);
            }

            if (isPackageChangeCompleted && inst.Order__c != null) {
                ChangePayload completionPayload = buildPayload('Package Change', inst, oldInst, quoteMap);
                completionPayload.updateOrderOnly = true;
                payloads.add(completionPayload);
            }
        }

        if (payloads.isEmpty()) {
            return;
        }

        System.enqueueJob(new InstallationChangeQueueable(payloads));
    }

    private static ChangePayload buildPayload(
        String changeType,
        Installation__c inst,
        Installation__c oldInst,
        Map<Id, SBQQ__Quote__c> quoteMap
    ) {
        ChangePayload payload = new ChangePayload();
        payload.installationId = inst.Id;
        payload.contractId = inst.Contract__c;
        payload.quoteId = inst.Quote__c;
        payload.packageId = inst.Package__c;
        payload.quoteLineGroupId = inst.Quote_Line_Group__c;
        payload.orderId = inst.Order__c != null ? inst.Order__c : oldInst.Order__c;
        payload.changeType = changeType;
        payload.oldPackageId = oldInst.Package__c;
        payload.newPackageId = inst.Package__c;
        payload.oldContractId = oldInst.Contract__c;
        payload.newContractId = inst.Contract__c;
        payload.oldQuoteId = oldInst.Quote__c;
        payload.newQuoteId = inst.Quote__c;

        Id quoteIdForOpp = inst.Quote__c != null ? inst.Quote__c : oldInst.Quote__c;
        if (quoteIdForOpp != null && quoteMap.containsKey(quoteIdForOpp)) {
            payload.opportunityId = quoteMap.get(quoteIdForOpp).SBQQ__Opportunity2__c;
        }

        return payload;
    }

    private static Boolean isStatusChange(Installation__c oldInst, Installation__c inst, String toStatus) {
        return inst.Installation_Order_Status__c == toStatus && oldInst.Installation_Order_Status__c != toStatus;
    }

    private static Boolean isContractChange(Installation__c oldInst, Installation__c inst) {
        return inst.Contract__c != oldInst.Contract__c && inst.Contract__c != null;
    }

    private static Boolean isRenewalQuote(Installation__c inst, Installation__c oldInst, Map<Id, SBQQ__Quote__c> quoteMap) {
        if (inst.Quote__c == null) {
            return false;
        }
        if (!quoteMap.containsKey(inst.Quote__c)) {
            return false;
        }
        return quoteMap.get(inst.Quote__c).SBQQ__Type__c == 'Renewal';
    }

    private static Boolean isPackageChangeInProgress(Installation__c oldInst, Installation__c inst) {
        if (inst.Change_Package_Status__c != 'In Progress') {
            return false;
        }
        if (oldInst.Change_Package_Status__c == 'In Progress') {
            return false;
        }
        return inst.Package__c != oldInst.Package__c;
    }

    private static Boolean isPackageChangeCompletion(Installation__c oldInst, Installation__c inst) {
        if (inst.Change_Package_Status__c != 'Completed') {
            return false;
        }
        return oldInst.Change_Package_Status__c != 'Completed';
    }

    public class InstallationChangeQueueable implements Queueable {
        private final List<ChangePayload> payloads;

        public InstallationChangeQueueable(List<ChangePayload> payloads) {
            this.payloads = payloads == null ? new List<ChangePayload>() : payloads;
        }

        public void execute(QueueableContext context) {
            if (payloads.isEmpty()) return;

            List<Installation_Change__c> recordsToInsert = new List<Installation_Change__c>();
            List<Installation_Change__c> recordsToUpdate = new List<Installation_Change__c>();
            for (ChangePayload payload : payloads) {
                if (payload.updateOrderOnly == true) {
                    Installation_Change__c existing = InstallationChangeService.findLatestPackageChange(payload);
                    if (existing != null && existing.Order__c == null && payload.orderId != null) {
                        existing.Order__c = payload.orderId;
                        recordsToUpdate.add(existing);
                    }
                    continue;
                }
                Installation_Change__c rec = new Installation_Change__c(
                    Installation__c = payload.installationId,
                    Contract__c = payload.contractId,
                    Quote__c = payload.quoteId,
                    Opportunity__c = payload.opportunityId,
                    Package__c = payload.packageId,
                    Quote_Line_Group__c = payload.quoteLineGroupId,
                    Order__c = payload.orderId,
                    // Order__c is set after field recreation to standard Order
                    Change_Type__c = payload.changeType,
                    Change_Date__c = System.now(),
                    Old_Package__c = payload.oldPackageId,
                    New_Package__c = payload.newPackageId,
                    Old_Contract__c = payload.oldContractId,
                    New_Contract__c = payload.newContractId,
                    Old_Quote__c = payload.oldQuoteId,
                    New_Quote__c = payload.newQuoteId
                );
                recordsToInsert.add(rec);
            }

            if (!recordsToInsert.isEmpty()) {
                insert recordsToInsert;
            }
            if (!recordsToUpdate.isEmpty()) {
                update recordsToUpdate;
            }
        }
    }

    private static Installation_Change__c findLatestPackageChange(ChangePayload payload) {
        if (payload == null || payload.installationId == null) return null;
        List<Installation_Change__c> matches = [
            SELECT Id, Order__c, New_Package__c, Package__c
            FROM Installation_Change__c
            WHERE Installation__c = :payload.installationId
              AND Change_Type__c = 'Package Change'
              AND Order__c = null
              AND (New_Package__c = :payload.newPackageId OR Package__c = :payload.packageId)
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
        return matches.isEmpty() ? null : matches[0];
    }

    public static Installation_Change__c buildChangeRecord(
        String changeType,
        Id installationId,
        Id quoteId,
        Id packageId,
        Id quoteLineGroupId,
        Id contractId,
        Id orderId
    ) {
        if (installationId == null || String.isBlank(changeType)) return null;
        return new Installation_Change__c(
            Installation__c = installationId,
            Contract__c = contractId,
            Quote__c = quoteId,
            Package__c = packageId,
            Quote_Line_Group__c = quoteLineGroupId,
            Order__c = orderId,
            Change_Type__c = changeType,
            Change_Date__c = System.now()
        );
    }
}