force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Installation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Installation_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Order_Status__c</fullName>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Implementation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Future Terminated</fullName>
            </value>
            <value>
                <fullName>Termination Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateInstallationLineScheduler.cls
public class CreateInstallationLineScheduler implements Schedulable
{
    public Id ordId;
    public void execute(SchedulableContext SC)
    {
        try
        {
            List<Order> ordList = [SELECT Id, Name, SBQQ__Quote__c, SBQQ__Quote__r.Installation__c FROM Order WHERE Id = :ordId]; //AND SBQQ__Quote__r.Installation__c != NULL];
            if(ordList != NULL && !ordList.isEmpty())
            {
                List<Installation__c> instList = [SELECT Id, Name,Installation_Order_Status__c FROM Installation__c WHERE Quote__c = :ordList[0].SBQQ__Quote__c AND Installation_Order_Status__c = 'Draft'];
                List<Id> instIdList = new List<Id>();
                for(Installation__c inst : instList)
                {
                    inst.Installation_Order_Status__c = 'Active';
                    instIdList.add(inst.Id);
                }
                CreateInstallationsController.goToInstallationLineCreation(instIdList);
                update instList;
            }
        }
        catch(Exception ex)
        {
            System.debug('ex --> ' + ex);
            System.debug('ex line --> ' + ex.getLineNumber());
            System.debug('ex stack --> ' + ex.getStackTraceString());
            Logger.error(ex.getMessage() + '\n\n' + ex.getLineNumber() + '\n\n' + ex.getStackTraceString());
        }
    }
}