force-app/main/default/objects/Installation__c/Installation__c.object-meta.xml
<CustomObject>
    <label>Installation</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Installation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Contract_Customer__c.field-meta.xml
<CustomField>
    <fullName>Contract_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria. Please choose B2B Account</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>B2B Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Archived B2B Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Contract Customer)</relationshipLabel>
    <relationshipName>Installations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Installation_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Order_Status__c</fullName>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Implementation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Future Terminated</fullName>
            </value>
            <value>
                <fullName>Termination Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>B2B Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation__c/fields/Vessel_Name__c.field-meta.xml
<CustomField>
    <fullName>Vessel_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel Name</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InstallationTriggerHandler.cls
public class InstallationTriggerHandler
{
    public static void beforeInsert(List<Installation__c> instList)
    {
        List<String> contractList = new List<String>();
        Map<String, Installation__c> contVessStatusMap = new Map<String, Installation__c>();
        Map<String, Installation__c> contOrgStatusMap = new Map<String, Installation__c>();
        for(Installation__c inst : instList)
        {
            contractList.add(inst.Contract_Customer__c);
            System.debug('vess name --> ' + inst.Vessel_Name__c);
            if(inst.Vessel_Name__c != NULL)
            {
                contVessStatusMap.put(inst.Contract_Customer__c + '-' + inst.Vessel_Name__c, inst);
            }
            else
            {
                contOrgStatusMap.put(inst.Contract_Customer__c + '-' + inst.Organisation_Name__c, inst);
            }
        }
        List<Installation__c> instRecList = [SELECT Id, Name, Contract__c, Contract_Customer__c, Organisation_Name__c, Vessel_Name__c, Installation_Order_Status__c FROM Installation__c WHERE Contract_Customer__c IN :contractList AND Installation_Order_Status__c = 'Active'];
        for(Installation__c inst : instRecList)
        {
            if(contOrgStatusMap.keySet().contains (inst.Contract_Customer__c + '-' + inst.Organisation_Name__c))
            {
                contOrgStatusMap.get(inst.Contract_Customer__c + '-' + inst.Organisation_Name__c).addError('Installation record already present, duplicate installation record not allowed.');
            }
            else if(contVessStatusMap.keySet().contains(inst.Contract_Customer__c + '-' + inst.Vessel_Name__c))
            {
                contVessStatusMap.get(inst.Contract_Customer__c + '-' + inst.Vessel_Name__c).addError('Installation record already present, duplicate installation record not allowed.');
            }
        }
    }
}